- alias: "Disable Camera When People At Home"
  trigger:
      - platform: state
        entity_id: binary_sensor.people_at_home
        to: "on"
        for: "00:01:00"
  action:
    - service: notify.tg_valaz
      data:
        title: "Дома есть люди"
        message: |
             {{"\U0001F4F9"}} Камера выключается.
    - service: script.tapo_c110_privacy_on
    - service: script.people_report

- alias: "Enable Camera When People Out Of Home"
  trigger:
      - platform: state
        entity_id: binary_sensor.people_at_home
        to: "off"
        for: "00:01:00"
  action:
    - service: notify.tg_valaz
      data:
        title: "Дома никого нет"
        message: |
             {{"\U0001F4F9"}} Камера включается.
    - service: script.tapo_c110_privacy_off
    
- alias: "Camera Shot When Door is opened"
  trigger:
  - platform: state
    entity_id: binary_sensor.tapo_camera_0069_motion_2
    to: "on"
  action:
    - service: notify.tg_valaz
      data:
        message: '{{"\U0001F6AA"}} Кто-то открыл дверь. Щас посмотрим.'
    - service: script.photo_video_tapo_c110_telegram